export const tiles = [
  "START",
  "Reflection",
  "Challenge",
  "Connection",
  "Jump forward 2 spaces!",
  "Reflection",
  "Challenge",
  "Connection",
  "Reflection",
  "Go back 3 spaces!",
  "Challenge",
  "Connection",
  "Reflection",
  "Challenge",
  "Connection",
  "Reflection",
  "Bonus turn! Roll the dice again.",
  "Challenge",
  "Connection",
  "Reflection",
  "Go back to 'START'!",
  "Reflection",
  "FINISH",
]; 